# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Corban Swain
tagline:             ''
description:         ''
url:                 http://corbanswain.com
baseurl:             ''
paginate:            5
paginate_path:       '/blog/page:num/'
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Corban Swain
  url:               http://corbanswain.com
  email:             corbanswain@gmail.com

# Plugins
plugins:
  - jekyll-paginate
  - pygments
  