# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Corban Swain
tagline:             'A Jekyll theme'
description:         'The blog of Corban Swain.'
url:                 http://corbanswain.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Corban Swain
  url:               http://corbanswain.com
  email:             corbanswain@gmail.com

# Custom vars
version:             0.0.1
